[[edge_functions]]
  function = "produto"
  path = "/produto.html"

[[edge_functions]]
  function = "produto" 
  path = "/produto/*"

[[redirects]]
  from = "/produto/*"
  to = "/produto.html"
  status = 200